# Generated by Django 2.2.7 on 2019-11-15 14:07

from django.db import migrations, models
import django.db.models.deletion
import hmmconfsite.demo.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('file_pnml', models.FileField(upload_to='')),
                ('file_startprob', models.FileField(upload_to='')),
                ('file_transcube', models.FileField(upload_to='')),
                ('file_transcube_d', models.FileField(upload_to='')),
                ('file_emitmat', models.FileField(upload_to='')),
                ('file_emitmat_d', models.FileField(upload_to='')),
                ('file_confmat', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=120)),
                ('state_id', models.IntegerField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Log')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseid', models.CharField(max_length=120)),
                ('index', models.IntegerField()),
                ('activity', models.CharField(max_length=120)),
                ('activity_id', models.CharField(max_length=120)),
                ('is_train', models.BooleanField()),
                ('logfwd_str', models.CharField(max_length=1000)),
                ('logfwd_before_obs_str', models.CharField(max_length=1000)),
                ('stateconf', models.FloatField(default=-1.0)),
                ('emitconf', models.FloatField(default=-1.0)),
                ('finalconf', models.FloatField(default=-1.0)),
                ('injected_distance', models.FloatField(default=-1.0)),
                ('completeness', models.FloatField(default=-1.0)),
                ('file_barplot_logfwd', sorl.thumbnail.fields.ImageField(blank=True, upload_to=hmmconfsite.demo.models.get_file_barplot_logfwd_fp)),
                ('file_barplot_logfwd_before_obs', sorl.thumbnail.fields.ImageField(blank=True, upload_to=hmmconfsite.demo.models.get_file_barplot_logfwd_before_obs_fp)),
                ('file_net_logfwd', sorl.thumbnail.fields.ImageField(blank=True, upload_to=hmmconfsite.demo.models.get_file_net_logfwd_fp)),
                ('file_net_logfwd_before_obs', sorl.thumbnail.fields.ImageField(blank=True, upload_to=hmmconfsite.demo.models.get_file_net_logfwd_before_obs_fp)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Log')),
                ('mode_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mode_state', to='demo.State')),
                ('mode_state_before_obs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mode_state_before_obs', to='demo.State')),
            ],
        ),
    ]
