# Generated by Django 2.2.7 on 2019-11-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='file_emitmat',
            new_name='file_logemitmat',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='file_emitmat_d',
            new_name='file_logemitmat_d',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='file_startprob',
            new_name='file_logstartprob',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='file_transcube',
            new_name='file_logtranscube',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='file_transcube_d',
            new_name='file_logtranscube_d',
        ),
    ]
