# Generated by Django 2.2.7 on 2019-11-15 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20191115_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='mode_state_before_obs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mode_state_before_obs', to='demo.State'),
        ),
    ]
