# Generated by Django 2.2.7 on 2019-11-16 13:14

from django.db import migrations
import hmmconfsite.demo.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20191115_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='file_barplot_case_length',
            field=sorl.thumbnail.fields.ImageField(blank=True, max_length=500, upload_to=hmmconfsite.demo.models.get_file_barplot_case_length_fp),
        ),
        migrations.AddField(
            model_name='log',
            name='file_barplot_case_unique_activity',
            field=sorl.thumbnail.fields.ImageField(blank=True, max_length=500, upload_to=hmmconfsite.demo.models.get_file_barplot_case_unique_activity_fp),
        ),
    ]
